### ISSUE TITLE
Run full node on server side to validate addition of new certs before adding to blockchain

### ISSUE THREAD

**Issue by chrismaree** [PangoSign/PangoSign#28]

**Comment by CarlBeek** [comment]
On server main.js:
var Web3 = require('web3');
var web3 = new Web3(new Web3.providers.HttpProvider("http://localhost:30305"));


Use geth command:

geth --testnet --fast --bootnodes "enode://20c9ad97c081d63397d7b685a412227a40e23c8bdc6688c6f37e97cfbc22d2b4d1db1510d8f61e6a8866ad7f0e17c02b14182d37ea7c3c8b9c2683aeb6b733a1@52.169.14.227:30303,enode://6ce05930c72abc632c58e2e4324f7c7ea478cec0ed4fa2528982cf34483094e9cbc9216e7aa349691242576d552a2a56aaeae426c5303ded677ce455ba1acd9d@13.84.180.240:30303" --port 30304 --rpc --rpcport 30305 --rpccorsdomain "*" --cache=1024
