### ISSUE TITLE
Find boostrap boilerplate

### ISSUE THREAD

**Issue by chrismaree** [PangoSign/PangoSign#61]

**Comment by chrismaree** [comment]
find a template that we like, pimp the shit out of it

**Comment by chrismaree** [comment]
Like these two thus far:
1) https://blackrockdigital.github.io/startbootstrap-creative/
2) https://blackrockdigital.github.io/startbootstrap-new-age/

both are open source

**Comment by chrismaree** [comment]
Another good free one
1) https://tympanus.net/codrops/2015/10/17/freebie-land-io-ui-kit-landing-page-template-html/

**Comment by chrismaree** [comment]
two more:
1) https://github.com/peterfinlan/Boxify
2) https://github.com/peterfinlan/Halcyon-Days

**Comment by chrismaree** [comment]
@av80r tell me what you think about the above 5. pick your fav

**Comment by CarlBeek** [comment]
Let's go with Land io.
I think theirs is the sexiest.

**Comment by chrismaree** [comment]
@av80r sounds good
