### ISSUE TITLE
Ability to change display mode in search from "grid" to "list"

### ISSUE THREAD

**Issue by chrismaree** [PangoSign/PangoSign#82]
I want to have a toggle to display the current certs in a more compacted way, say a data table JS list that is orderable by values within the cards. for example, sort by date or candidate name. in the context of the issuer, this will be useful. less useful in other context so we can consider only showing it there. thoughts @av80r ?

**Comment by CarlBeek** [comment]
I agree, it is only really of use to Institutes.

**Comment by CarlBeek** [comment]
On hard-reload, although Grid is selected, no certificates are shown until the grid toggle is selected again.

**Comment by chrismaree** [comment]
chose not to use this
